name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: StupidityDB
          token: ${{ secrets.PERSONAL_TOKEN }}
          ignore_fail: true
          base: main
          head: main
